# -*- coding: utf-8 -*-
"""Oficina 06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107m7xmgrKtu2lE8W5WKMnacIHSowyhuT
"""

#Escreva um código usando enumerate para exibir os índices e valores da lista ["maçã", "banana", "uva"].
frutas = ["maçã", "banana", "uva"]

for indice, fruta in enumerate(frutas):

    print(f"Índice {indice}: {fruta}")

#Crie uma lista com os números pares de 1 a 10 usando List Comprehension.
pares = [x for x in range(1,11) if x%2==0]
print(pares)

#Escreva um programa que use map para multiplicar cada elemento da lista [1, 2, 3, 4] por 3
lista = [1, 2, 3, 4]
multiplicar = list(map(lambda x: x*3, lista))
print(multiplicar)

#Escreva um programa que use enumerate e List Comprehension para criar uma lista de tuplas com os índices e valores ao quadrado de [2, 4, 6]
lista2 = [2, 4, 6]
elevar_quadradro = [(indice, valor**2) for indice, valor in enumerate(lista2)]

print(elevar_quadradro)